api_client_base_url = ""
api_client_id = ""
api_client_secret = ""
api_client_scopes = [""]

api_projects_base_url = ""
api_accounts_base_url = ""

# The role we will get a list of users from.
# Users without this role won't get any accounts
list_users_role = "category/service"

# Names of SLURM accounts which will not be modified by the script.
unmanaged_accounts = []
# Names of SLURM users which will not be modified by the script.
unmanaged_users = []

# Users with no other account will be added to this one
no_project_account = "no-project"

# All users will have this account set as their default account.
default_account = ""

# Users who do not exist in list_users_role, but do exist in SLURM, will be moved to this account.
inactive_account = ""

# Define extra accounts portal services to map to slurm accounts.
[extra_account_mapping]
"category/service" = ["slurm-account-name"]
