ldap_server_addr = "ldap.example.com" # The address of your ldap server.
ldap_search_base = "ou=people,dc=example,dc=com" # The search base for ldap.
ldap_search_filter =  "(description=spam:eggs)" # A filter to apply to the search.

required_slurm_accounts = ["planetexpress"] # SLURM accounts (as mapped by ldap_tag_mapping) which are required before user is synced.

daemon_sleep_time = 300 # Time between syncs when in daemon mode.

# A map of ldap tags to slurm accounts.
# An ldap tag can manage multiple slurm accounts
# But a slurm account can't be associated with multiple ldap tags,
# this will cause unxpected behaviour.
[ldap_tag_mapping]
"spam:eggs" = ["example", "bacon"]
"spam:ham" = ["cheese"]
